Optimized.

diff --git a/remotekeyboard-login b/remotekeyboard-login
--- a/remotekeyboard-login
+++ b/remotekeyboard-login
@@ -17,7 +17,10 @@ fi
 
 # netstat -lnt | awk '$6 == "LISTEN" && $4 ~ ".2323"'
 if ! nc -z localhost "$TELNET_PORT"; then
-    ssh -fNT -L$TELNET_PORT:localhost:$TELNET_PORT "$HOSTNAME"
+    if ! ssh -fNT -L$TELNET_PORT:localhost:$TELNET_PORT "$HOSTNAME"; then
+        echo "Could not establish port forwarding via ssh."
+        exit 1
+    fi
 fi
 
 ## https://github.com/ypid/scripts/blob/master/telnet-login
